name: Python CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: true
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

        # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # Caches the installed Python packages

        # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pyproject.toml

      - name: Lint with Ruff (Flake8-compatible)
        run: |
          ruff check src/
      - name: Format with Ruff (Black-compatible)
        run: |
          ruff format src/
